development:
  adapter: async

test:
  adapter: async


# # Local Host Production
# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: Cacophony_production
# Keep trying lol

# Heroku Production
  production:
    adapter: redis
    url:  redis://redistogo:63caf45797d40cfe10a6d8ed2ff5728d@sole.redistogo.com:10602/
